name: Actions Ecosystem Action Push Tag
description: Push a Git tag.
author: step-security
inputs:
  tag:
    description: A Git tag name.
    required: true
  message:
    description: A message for the Git tag.
    required: false
runs:
  using: docker
  image: 'docker://ghcr.io/step-security/action-push-tag:v1.0.1@sha256:86f3be5659e8ff8843f7021b0f57787aa2422613f6dadd4f0e8b20ff9cf577bf' #v1.0.1
branding:
  icon: search
  color: yellow
